name: Run Main Script

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch: 

jobs:
  run-main-script:
    runs-on: ubuntu-latest
    
    env:
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      SMTP_RECIPIENT: ${{ secrets.SMTP_RECIPIENT }}
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      VERIFIED_EMAIL: ${{ secrets.VERIFIED_EMAIL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Run Main Script
        run: python main.py
