name: Run Pytest on Pull Requests

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
            pytest -vv  \
                --disable-warnings \
                --cov=src \
                --cov-config=.coveragerc \
                --cov-report=term-missing \
                --cov-fail-under=85 \
                tests/
            
